name: Versioning and Overwrite & Publish

on:
    workflow_dispatch:
        inputs:
            overwrite_tag:
                description: "Overwrite existing tag? (main branch will always set this to false)"
                required: true
                default: "false"
                type: choice
                options:
                    - "true"
                    - "false"
            version_type:
                description: "Version increment type (major, minor, patch)"
                required: false
                default: "patch"
                type: choice
                options:
                    - major
                    - minor
                    - patch
            build_mode:
                description: "Build mode (dev or release)"
                required: true
                default: "release"
                type: choice
                options:
                    - dev
                    - release

jobs:
    version-and-publish:
        runs-on: ubuntu-latest

        steps:
            # 1. Checkout repository
            - name: Checkout repository
              uses: actions/checkout@v3

            # 2. Setup Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20 # 로컬 환경과 동일한 Node.js 버전

            # 3. Run create_npmrc.sh script to generate .npmrc (npmrc를 임시로 생성하는 로직)
            - name: Create .npmrc file
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  chmod +x .github/create_npmrc.sh
                  ./.github/create_npmrc.sh

            # 4. Determine current branch
            - name: Get current branch
              id: branch
              run: |
                  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
                  echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV

            # 5. Install dependencies
            - name: Install dependencies
              run: npm install

            # 6. Determine version
            - name: Determine version
              run: |
                  if [[ "${{ env.CURRENT_BRANCH }}" == "main" ]]; then
                      # Main branch: Increment version in package.json
                      CURRENT_VERSION=$(cat package.json | jq -r '.version')
                      IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

                      if [[ "${{ inputs.version_type }}" == "major" ]]; then
                          MAJOR=$((MAJOR + 1))
                          MINOR=0
                          PATCH=0
                      elif [[ "${{ inputs.version_type }}" == "minor" ]]; then
                          MINOR=$((MINOR + 1))
                          PATCH=0
                      else
                          PATCH=$((PATCH + 1))
                      fi

                      NEW_VERSION="$MAJOR.$MINOR.$PATCH"
                      echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

                      jq ".version = \"$NEW_VERSION\"" package.json > package.tmp.json
                      mv package.tmp.json package.json
                  else
                      # Non-main branch: Use branch-specific version
                      CURRENT_VERSION=$(cat package.json | jq -r '.version')
                      NEW_VERSION="$CURRENT_VERSION-${{ env.CURRENT_BRANCH }}"
                      echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
                  fi

            # 7. Commit version update (main branch only)
            - name: Commit version update
              if: ${{ env.CURRENT_BRANCH == 'main' }}
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"
                  git add package.json
                  git commit -m "Bump version to $NEW_VERSION"
                  git push origin main

            # 8. Build project
            - name: Build project
              run: |
                  if [[ "${{ inputs.build_mode }}" == "dev" ]]; then
                      npm run build:dev
                  else
                      npm run build:release
                  fi

            # 9. Create and push tag (main branch only)
            - name: Create and push tag
              run: |
                  if [[ "${{ inputs.build_mode }}" == "dev" ]]; then
                      # dev Mode일 경우 태그에 dev 추가
                      git tag "v${{ env.NEW_VERSION }}-dev"
                      git push origin "v${{ env.NEW_VERSION }}-dev"
                  elif [[ "${{ env.CURRENT_BRANCH }}" == "main" ]]; then
                      git tag "v${{ env.NEW_VERSION }}"
                      git push origin "v${{ env.NEW_VERSION }}"
                  fi

            # 10. Publish package
            - name: Publish package
              run: |
                  if [[ "${{ env.CURRENT_BRANCH }}" == "main" ]]; then
                      if [[ "${{ inputs.build_mode }}" == "dev" ]]; then
                          # dev 모드 활성화
                          TEMP_VERSION="${{ env.NEW_VERSION }}-dev"
                          jq ".version = \"$TEMP_VERSION\"" package.json > package.tmp.json
                          mv package.tmp.json package.json
                          npm publish --tag dev
                          git checkout -- package.json # Revert changes to package.json
                      else
                          npm publish
                      fi
                  else
                      # Non-main branch: Use temporary version for publishing
                      TEMP_VERSION="${{ env.NEW_VERSION }}"
                      if [[ "${{ inputs.build_mode }}" == "dev" ]]; then
                          # dev 모드 활성화
                          TEMP_TAG="${{ env.CURRENT_BRANCH }}-dev"
                          jq ".version = \"$TEMP_VERSION\"" package.json > package.tmp.json
                          mv package.tmp.json package.json
                          npm publish --tag "$TEMP_TAG"
                          git checkout -- package.json # Revert changes to package.json
                      else
                          jq ".version = \"$TEMP_VERSION\"" package.json > package.tmp.json
                          mv package.tmp.json package.json
                          npm publish --tag "${{ env.CURRENT_BRANCH }}"
                          git checkout -- package.json # Revert changes to package.json
                      fi
                  fi
